CREATE DATABASE IF NOT EXISTS company;

USE company;

CREATE TABLE employees(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) DEFAULT NULL,
    salary INT(11) DEFAULT NULL
);

-- store procedure to update or creata an employee
-- autogenerated by MysqlWorkbench
CREATE DEFINER=`root`@`localhost` PROCEDURE `employeeAddOrEdit`(
  IN _id INT,
  IN _name VARCHAR(50),
  IN _salary INT
)
BEGIN 
  IF _id = 0 THEN
	BEGIN
		INSERT INTO employees (name, salary) VALUES (_name, _salary);
		SET _id = LAST_INSERT_ID();
    END;
  ELSE
	BEGIN
    UPDATE employees SET name = _name, salary = _salary WHERE id = _id;
    END;
  END IF;
  SELECT _id AS 'id';
END

--You can you "mockaroo.com" to generate random values

insert into employees (name, salary) values ('Constanta', '10773');
insert into employees (name, salary) values ('Antonetta', '17120');
insert into employees (name, salary) values ('Andeee', '13751');
insert into employees (name, salary) values ('Margie', '11041');
insert into employees (name, salary) values ('Tate', '14196');
insert into employees (name, salary) values ('Clive', '14947');
insert into employees (name, salary) values ('Candida', '17903');
insert into employees (name, salary) values ('Judye', '14027');
insert into employees (name, salary) values ('Ban', '15014');
insert into employees (name, salary) values ('Tallulah', '13363');
insert into employees (name, salary) values ('Adolf', '19676')

